#!/usr/bin/env node

var fs = require('fs'),
    path = require("path"),
	infile = process.argv[2];

function preprocess(file){
	var filePath = path.dirname(file);

	return fs.readFileSync(file, 'utf-8').
		replace(/\/\/\s*@include\s+"([^"]*)"/g, function(i,f){ return preprocess(path.resolve(filePath, f)); });
}

console.log(preprocess(infile));
